# Generated by Django 4.2.1 on 2024-02-01 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='digital',
        ),
    ]
