# Generated by Django 4.2.1 on 2024-02-01 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_product_digital'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='scale',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
