# Generated by Django 4.2.1 on 2024-02-01 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_scale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='state',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='zipcode',
        ),
    ]
